---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/tupresen/public_html/auditconsultores.cl
    - /bin/mkdir -p $DEPLOY_PATH
    - /bin/rsync -av --delete --exclude ".git/" --exclude ".github/" ./ $DEPLOY_PATH/
